# .woodpecker.yml
# CI/CD configuration for devenv (Emacs build testing)
#
# MULTI-FORGE SUPPORT:
# - GitLab (private): Uses SSH clone with deploy key (requires ssh_key secret)
# - GitHub (public): Uses default HTTPS clone (no secret needed)
#
# ARCHITECTURE:
# - Uses custom base image with dependencies pre-installed (see ci/Dockerfile)
# - Layer tests run in PARALLEL - failures are isolated, don't block other layers
# - macOS-specific code paths are skipped (Linux CI only)
#
# IMAGE MAINTENANCE:
# - If you add new dependencies, rebuild: ./ci/build-image.sh --push
# - Image source: ci/Dockerfile

when:
  event: [push, pull_request, manual]

# Clone configuration:
# - GitHub: Public repo, uses default HTTPS clone (no SSH needed)
# - GitLab: Private repo, uses SSH clone with deploy key
clone:
  - name: clone
    image: woodpeckerci/plugin-git:2.5.2
    settings:
      depth: 1
    when:
      - evaluate: 'CI_FORGE == "github"'

  - name: clone-gitlab
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -t ed25519 gitlab.com >> ~/.ssh/known_hosts 2>/dev/null
        git clone --depth=1 --branch=${CI_COMMIT_BRANCH} git@gitlab.com:${CI_REPO}.git .
        git fetch origin ${CI_COMMIT_SHA} --depth=1
        git checkout ${CI_COMMIT_SHA}
        chmod -R a+rwX . || true
    when:
      - evaluate: 'CI_FORGE == "gitlab"'

variables:
  - &ci_image "jlipworth/gnu-files-ci:latest"
  - &gcc_version "12"
  - &emacs_image "debian:bookworm-slim"

steps:
  # ═══════════════════════════════════════════════════════════════════════════
  # CORE BUILD TESTS
  # ═══════════════════════════════════════════════════════════════════════════

  - name: build-and-verify
    image: *emacs_image
    environment:
      DEBIAN_FRONTEND: noninteractive
      CI: "true"
      CI_INSTALL: "true"
      GCC_VERSION: *gcc_version
    commands:
      - set -ex
      - chmod +x build_emacs30.sh common_utils.sh || true
      # Build Emacs (installs all dependencies)
      - ./build_emacs30.sh
      - echo "=== Build complete, verifying Emacs ==="
      - /usr/local/bin/emacs --version
      # Verify Spacemacs compatibility
      - echo "=== Testing Spacemacs compatibility ==="
      - git clone --depth 1 --branch develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
      - /usr/local/bin/emacs --batch --eval "(progn
          (require 'package)
          (setq package-archives '((\"melpa\" . \"https://melpa.org/packages/\")
                                   (\"gnu\" . \"https://elpa.gnu.org/packages/\")))
          (package-initialize)
          (message \"Package system initialized successfully\"))"
      - echo "=== Spacemacs compatibility check passed! ==="

  # ═══════════════════════════════════════════════════════════════════════════
  # LAYER TESTS - Run in parallel immediately (depends_on: [])
  # All use the pre-built CI image with dependencies already installed
  # ═══════════════════════════════════════════════════════════════════════════

  - name: layer-shell
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make shell-layer

  - name: layer-git
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make git-layer

  - name: layer-yaml
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make yaml

  - name: layer-markdown
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make markdown

  - name: layer-vimscript
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make vimscript

  - name: layer-latex
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make latex

  - name: layer-python
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make python

  - name: layer-python-env
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make python-env

  - name: layer-r
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make r

  - name: layer-c_cpp
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make c_cpp

  - name: layer-sql
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make sql

  - name: layer-js
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make js

  - name: layer-html_css
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make html_css

  - name: layer-docker
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make docker

  - name: layer-ocaml
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make ocaml

  - name: layer-terraform
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make terraform

  - name: layer-rust
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make rust

  - name: layer-ai-tools
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make ai-tools

  - name: layer-cli_tools
    image: *ci_image
    depends_on: []
    environment:
      CI: "true"
      DEBIAN_FRONTEND: noninteractive
    commands:
      - make cli_tools

  # ═══════════════════════════════════════════════════════════════════════════
  # LINTING
  # ═══════════════════════════════════════════════════════════════════════════

  - name: lint-scripts
    image: koalaman/shellcheck-alpine:stable
    depends_on: []
    commands:
      # Use project's .shellcheckrc for suppressions
      - shellcheck --source-path=SCRIPTDIR -x *.sh

  # ═══════════════════════════════════════════════════════════════════════════
  # RENOVATE BOT (runs on cron schedule only)
  # Scans GitHub repo and creates PRs for dependency updates
  # GitLab is secondary (personal modifications) - no Renovate there
  # Setup: Requires github_pat secret and weekly cron job in Woodpecker
  # ═══════════════════════════════════════════════════════════════════════════

  - name: renovate
    image: renovate/renovate:latest
    depends_on: []
    environment:
      RENOVATE_TOKEN:
        from_secret: github_pat
      RENOVATE_PLATFORM: github
      RENOVATE_REPOSITORIES: jlipworth/devenv
      RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@noreply.github.com>"
      LOG_LEVEL: info
    commands:
      - renovate
    when:
      - event: cron
