# .woodpecker/build.yml
# Core Emacs build and Spacemacs compatibility test

when:
  event: [push, pull_request, manual]

# Conditional clone based on repo
clone:
  gitlab-clone:
    image: alpine/git
    when:
      - evaluate: 'CI_REPO == "jlipworth/GNU_files"'
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keyscan -t ed25519 gitlab.com >> ~/.ssh/known_hosts 2>/dev/null
      - git clone --depth=1 --branch=$CI_COMMIT_BRANCH git@gitlab.com:jlipworth/GNU_files.git .
      - git fetch origin $CI_COMMIT_SHA --depth=1
      - git checkout $CI_COMMIT_SHA
  github-clone:
    image: woodpeckerci/plugin-git
    when:
      - evaluate: 'CI_REPO == "jlipworth/devenv"'

variables:
  - &gcc_version "12"
  - &emacs_image "debian:bookworm-slim"

steps:
  - name: build-and-verify
    image: *emacs_image
    environment:
      DEBIAN_FRONTEND: noninteractive
      CI: "true"
      CI_INSTALL: "true"
      GCC_VERSION: *gcc_version
    commands:
      - set -ex
      - chmod +x build_emacs30.sh common_utils.sh || true
      - ./build_emacs30.sh
      - echo "=== Build complete, verifying Emacs ==="
      - /usr/local/bin/emacs --version
      - echo "=== Testing Spacemacs compatibility ==="
      - git clone --depth 1 --branch develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
      - /usr/local/bin/emacs --batch --eval "(progn
          (require 'package)
          (setq package-archives '((\"melpa\" . \"https://melpa.org/packages/\")
                                   (\"gnu\" . \"https://elpa.gnu.org/packages/\")))
          (package-initialize)
          (message \"Package system initialized successfully\"))"
      - echo "=== Spacemacs compatibility check passed! ==="
