# .woodpecker/notify-failure.yml
# Discord notification after any dependent pipeline fails

when:
  event: [push, pull_request, manual]

skip_clone: true

depends_on:
  - build
  - layers
  - lint
  - noadmin

runs_on: [failure]

steps:
  - name: notify-failure
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        ❌ **Failed**: {{repo.name}} ({{commit.branch}})
        {{commit.message}}
        {{build.link}}
