# .woodpecker/notify.yml
# Discord notification after main pipeline completes

when:
  event: [push, pull_request, manual]

skip_clone: true

depends_on:
  - build
  - layers
  - lint

runs_on: [success, failure]

steps:
  - name: notify-success
    image: appleboy/drone-discord
    when:
      - status: success
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        ✅ **Success**: {{repo.name}} ({{commit.branch}})
        {{commit.message}}
        {{build.link}}

  - name: notify-failure
    image: appleboy/drone-discord
    when:
      - status: failure
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        ❌ **Failed**: {{repo.name}} ({{commit.branch}})
        {{commit.message}}
        {{build.link}}
